server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写)
      #转发到具体的服务实例。默认为false，
      #设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
      discovery:
        locator:
          enabled: true
      routes:
        - id: 163  #网关路由到网易官网
          uri: http://www.163.com/
          predicates:
            - Path=/163/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
