spring:
  application:
    name: eureka-server
server:
  port: 8001
eureka:
  server:
    enable-self-preservation: false  #注册中心的保护机制
  instance:
    #不使用主机名来定义注册中心的地址，而使用IP地址的形式，
    #如果设置了eureka.instance.ip-address 属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
    prefer-ip-address: true
    #设置当前实例的主机名称
    hostname: ${spring.cloud.client.ip-address}
    #区分同一服务中不同实例的唯一标识
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    #默认true 启动服务注册；false不会向Eureka Server注册中心注册自己的信息
    register-with-eureka: true
    #默认true，检索服务；false不会向Eureka Server注册中心获取注册信息
    fetch-registry: false
    service-url: #指定服务注册中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

